- hosts: all
  become: true
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: create environment file
      ansible.builtin.template:
        src: templates/.env.j2
        dest: /etc/.env
      tags: deploy

    - name: Copy docker-compose.yml
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: /etc/docker-compose.yml
      tags: deploy
