- hosts: all
  become: true
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Copy docker-compose.yml
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: /etc/docker-compose.yml
      tags: deploy

    - name: Ensure Docker is started
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Run Docker Compose
      community.docker.docker_compose:
        project_src: /etc
        state: present
      tags: deploy

- hosts: webservers
  vars:
    datadog_api_key: "{{ datadog_api_key_vault }}"
  become: true
  tasks:
    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.dd.agent
      tags: datadog
    - name: http check
      ansible.builtin.template:
        src: templates/http_check.j2
        dest: /etc/datadog-agent/conf.d/http_check.d/conf.yaml
      tags: datadog
